In [1]:
import requests
import pandas as pd
import numpy as np
import time

In [2]:
finals = []
offset = 0
artworks_df = pd.DataFrame(columns=('artwork_id','title','category','medium','date','height_cm','width_cm','image_versions','image_url','collecting_institution','image_url_is_template'))

In [27]:
# url = 'https://api.artsy.net/api/genes'

while offset < 200000:
    params = {'size':'100',
              'offset':offset,
#               'gene_id':'531df66f275b24e993000009',
              'xapp_token':'eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IiIsInN1YmplY3RfYXBwbGljYXRpb24iOiI2YzY0ZTZjZC1lMDBmLTQ1NzEtOGZlZi1mYzQ3NmNkODNmZjkiLCJleHAiOjE2OTM4MjQ2MzAsImlhdCI6MTY5MzIxOTgzMCwiYXVkIjoiNmM2NGU2Y2QtZTAwZi00NTcxLThmZWYtZmM0NzZjZDgzZmY5IiwiaXNzIjoiR3Jhdml0eSIsImp0aSI6IjY0ZWM3YmY2NWFmMzU2MDAwYTk2OThmZiJ9.FI2Y7A9Ry1MRaq_N6MdSWyOBXwro4PTUzzHt0TL6aKs'}

    url = 'https://api.artsy.net/api/artworks?'

    response = requests.get(url,params=params).json()

    artworks = response['_embedded']['artworks']
#     artworks_ = [] 

    for artwork in artworks:
        artwork_dict = {}
        artwork_dict['artwork_id'] = artwork['id']
        artwork_dict['title'] = artwork['title']
        artwork_dict['category'] = artwork['category']
        artwork_dict['medium'] = artwork['medium']
        artwork_dict['date'] = artwork['date']
        artwork_dict['height_cm'] = artwork['dimensions']['cm']['height']
        artwork_dict['width_cm'] = artwork['dimensions']['cm']['width']
    
        try:
            artwork_dict['image_versions'] = artwork['image_versions']
            artwork_dict['image_url'] = artwork['_links']['image']['href']
            artwork_dict['image_url_is_template'] = artwork['_links']['image']['templated']
            artwork_dict['collecting_institution'] = artwork['collecting_institution']

        except:
            artwork_dict['image_versions'] = None
            artwork_dict['image_url'] = None
            artwork_dict['image_url_is_template'] = None
#         artworks_.append(artwork_dict)
        artworks_temp = pd.DataFrame([artwork_dict])
        artworks_df = pd.concat([artworks_df, artworks_temp], ignore_index=True)
#     finals.append(artworks_)
    offset+=100
    time.sleep(.5)

KeyError: '_embedded'

In [43]:
artworks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26000 entries, 0 to 25999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   artwork_id              26000 non-null  object
 1   title                   26000 non-null  object
 2   category                25999 non-null  object
 3   medium                  25998 non-null  object
 4   date                    26000 non-null  object
 5   height_cm               12680 non-null  float64
 6   width_cm                12504 non-null  float64
 7   image_versions          25893 non-null  object
 8   image_url               25893 non-null  object
 9   collecting_institution  25893 non-null  object
 10  image_url_is_template   25893 non-null  object
dtypes: float64(2), object(9)
memory usage: 2.2+ MB

In [41]:
artworks_df.head()

,artwork_id,title,category,medium,date,height_cm,width_cm,image_versions,image_url,collecting_institution,image_url_is_template
0,4d8b92eb4eb68a1b2c000968,Der Kuss (The Kiss),Painting,Oil and gold leaf on canvas,1907-1908,180.1,180.1,"[large, larger, medium, medium_rectangle, norm...",https://d32dm0rphc51dk.cloudfront.net/NOpIAwQa...,"Österreichische Galerie Belvedere, Vienna",True
1,4d8b92ee4eb68a1b2c0009ab,The Third of May,Painting,Oil on canvas,1814,266.2,345.2,"[square, small, large_rectangle, large, tall, ...",https://d32dm0rphc51dk.cloudfront.net/m4X41Fun...,"Museo Nacional del Prado, Madrid",True
2,4d8b93394eb68a1b2c0010fa,The Company of Frans Banning Cocq and Willem v...,Painting,Oil on canvas,1642,363.2,437.4,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/IG8ZLvVm...,"Rijksmuseum, Amsterdam",True
3,4d8b937c4eb68a1b2c001722,Mona Lisa,Painting,Oil on poplar,ca. 1503-1506,77.0,53.1,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/5L1xjKC_...,Musée du Louvre,True
4,4d8b93b04eb68a1b2c001b9d,Luncheon on the Grass (Le Déjeuner sur l'herbe),Painting,Oil on canvas,1863,208.3,264.2,"[large, large_rectangle, larger, medium_rectan...",https://d32dm0rphc51dk.cloudfront.net/zFA7cwdk...,"Musée d'Orsay, Paris",True

In [4]:
artworks_df['category'].value_counts()

Print                                      15893
Drawing, Collage or other Work on Paper     4295
                                            2257
Painting                                    2060
Sculpture                                    817
Photography                                  414
Design/Decorative Art                         82
Other                                         62
Architecture                                  46
Books and Portfolios                          37
Mixed Media                                   17
Textile Arts                                  13
Posters                                        6
Name: category, dtype: int64

In [40]:
artworks_df['image_versions'].value_counts()

[large, large_rectangle, larger, medium, medium_rectangle, normalized, small, square, tall]    7401
[large_rectangle, larger, medium, medium_rectangle, normalized, small, square, tall]           2949
[large, large_rectangle, larger, medium, medium_rectangle, normalized, small, square]          2595
[large, large_rectangle, larger, medium, medium_rectangle, normalized, small, tall]            2310
[large, large_rectangle, larger, medium, medium_rectangle, normalized, square, tall]           2142
                                                                                               ...
[large_rectangle, larger, small, square]                                                          1
[large_rectangle, larger, square]                                                                 1
[large, larger, small, square]                                                                    1
[large_rectangle, larger, medium, medium_rectangle, normalized, small, square, tall, large]       1
[large_rectangle, larger, tall]                                                                   1
Name: image_versions, Length: 448, dtype: int64

In [59]:
a = 1
# artworks_df.loc[artworks_df['image_versions'].isna().index, 'image_versions']= [a for x in artworks_df[artworks_df['image_versions'].isna()]['image_versions']]
artworks_df['image_versions'].fillna(1)

0        [large, larger, medium, medium_rectangle, norm...
1        [square, small, large_rectangle, large, tall, ...
2        [large, large_rectangle, larger, medium, mediu...
3        [large, large_rectangle, larger, medium, mediu...
4        [large, large_rectangle, larger, medium_rectan...
                               ...
25995    [large, large_rectangle, larger, medium, mediu...
25996    [large, large_rectangle, larger, medium, mediu...
25997    [large, large_rectangle, larger, medium, mediu...
25998    [large, large_rectangle, larger, medium, mediu...
25999    [large, large_rectangle, larger, medium, mediu...
Name: image_versions, Length: 26000, dtype: object

In [76]:
pd.Series([[] for x in range(107)], index=artworks_df[artworks_df['image_versions'].isna()].index)

272      []
870      []
1221     []
1363     []
1962     []
         ..
24511    []
24512    []
24513    []
24514    []
24515    []
Length: 107, dtype: object

In [77]:
artworks_df.loc[artworks_df[artworks_df['image_versions'].isna()].index, 'image_versions'] = pd.Series([[] for x in range(107)], index=artworks_df[artworks_df['image_versions'].isna()].index)

In [80]:
artworks_df["large"] = artworks_df['image_versions'].apply(lambda x: "large" in x)
artworks_df["large_rectangle"] = artworks_df['image_versions'].apply(lambda x: "large_rectangle" in x)
artworks_df["larger"] = artworks_df['image_versions'].apply(lambda x: "larger" in x)
artworks_df["medium"] = artworks_df['image_versions'].apply(lambda x: "medium" in x)
artworks_df["medium_rectangle"] = artworks_df['image_versions'].apply(lambda x: "medium_rectangle" in x)
artworks_df["normalized"] = artworks_df['image_versions'].apply(lambda x: "normalized" in x)
artworks_df["small"] = artworks_df['image_versions'].apply(lambda x: "small" in x)
artworks_df["square"] = artworks_df['image_versions'].apply(lambda x: "square" in x)
artworks_df["tall"] = artworks_df['image_versions'].apply(lambda x: "tall" in x)

In [81]:
artworks_df

,artwork_id,title,category,medium,date,height_cm,width_cm,image_versions,image_url,collecting_institution,image_url_is_template,large,large_rectangle,larger,medium_rectangle,normalized,small,square,tall
0,4d8b92eb4eb68a1b2c000968,Der Kuss (The Kiss),Painting,True,1907-1908,180.1,180.1,"[large, larger, medium, medium_rectangle, norm...",https://d32dm0rphc51dk.cloudfront.net/NOpIAwQa...,"Österreichische Galerie Belvedere, Vienna",True,True,False,True,True,True,True,True,True
1,4d8b92ee4eb68a1b2c0009ab,The Third of May,Painting,True,1814,266.2,345.2,"[square, small, large_rectangle, large, tall, ...",https://d32dm0rphc51dk.cloudfront.net/m4X41Fun...,"Museo Nacional del Prado, Madrid",True,True,True,True,True,True,True,True,True
2,4d8b93394eb68a1b2c0010fa,The Company of Frans Banning Cocq and Willem v...,Painting,True,1642,363.2,437.4,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/IG8ZLvVm...,"Rijksmuseum, Amsterdam",True,True,True,True,True,True,True,True,True
3,4d8b937c4eb68a1b2c001722,Mona Lisa,Painting,True,ca. 1503-1506,77.0,53.1,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/5L1xjKC_...,Musée du Louvre,True,True,True,True,True,True,True,True,True
4,4d8b93b04eb68a1b2c001b9d,Luncheon on the Grass (Le Déjeuner sur l'herbe),Painting,True,1863,208.3,264.2,"[large, large_rectangle, larger, medium_rectan...",https://d32dm0rphc51dk.cloudfront.net/zFA7cwdk...,"Musée d'Orsay, Paris",True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25995,53559d87cd530e850c000166,"View of Houses in Delft, Known as ‘The Little ...",Painting,True,ca. 1658,54.3,44.0,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/6sSY1BE4...,,True,True,True,True,True,True,True,True,True
25996,53559fedb202a3262000016a,The Battle of Terheide,Painting,True,1657,170.0,289.0,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/fOlaqjoa...,,True,True,True,True,True,True,True,True,True
25997,5357d09c7622dd0ff400002a,"Isaac and Rebecca, Known as ‘The Jewish Bride’",Painting,True,ca. 1665 -1669,121.5,166.5,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/T8zyOM1P...,,True,True,True,True,True,True,True,True,True
25998,5357d2cfa09a679102000045,"Portrait of a Woman, Possibly Maria Trip",Painting,True,1639,107.0,82.0,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/UJxHMaBg...,,True,True,True,True,True,True,True,True,True
25999,5357d5288b3b813fcd00004a,"The Wardens of the Amsterdam Drapers’ Guild, K...",Painting,True,1662,191.5,279.0,"[large, large_rectangle, larger, medium, mediu...",https://d32dm0rphc51dk.cloudfront.net/kZMo5_gj...,,True,True,True,True,True,True,True,True,True